# Generated by Django 4.0.4 on 2022-05-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_feature_event_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(default='', max_length=90, verbose_name='Свойство события'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(default='', max_length=500),
        ),
    ]
