# Generated by Django 4.0.4 on 2022-05-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_feature_title_alter_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateTimeField(verbose_name='Дата начала события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='', verbose_name='Описание события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Частное?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество билетов'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Название события'),
        ),
    ]
